app/urls.py
from django.urls import path

from . import views
from django.views.static import serve
# 设置命名空间，防止多个app中的url重名
# 访问view的规则： app:index
app_name = 'app'

urlpatterns = [
    path("index", views.index, name="index"),

    path("glove", views.glove, name="glove"),
    path("glove/state", views.state, name="state"),
    path("glove/adduser", views.adduser, name="adduser"),
    path("glove/getdata", views.getdata, name="getdata"),
    path("glove/result", views.result, name="result"),
    path("glove/stop", views.stop, name="stop"),
    path("glove/train", views.train, name="train"),
    path("glove/setname", views.setname, name="setname"),
    path("glove/setlabel", views.setlabel, name="setlabel"),
    path("glove/savedata", views.savedata, name="savedata"),
    path("glove/train_model", views.train_model, name="train_model"),
    path("glove/transfer_data", views.transfer_data, name="transfer_data"),
    path("glove/update_acc", views.update_acc, name="update_acc"),
    path("glove/get_ten_acc", views.get_ten_acc, name="get_ten_acc"),
]

cognitive_rehabilitation_system/urls.py
from django.contrib import admin
from django.urls import include, path
# include : 截断url，将剩余部分交给下一个url匹配
urlpatterns = [
    path("app/", include("app.urls")),
    path("admin/", admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.
# 下边类似于数据库的表，每个对象是一行数据，每个属性是一列数据
class User(models.Model):
    username = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    sex = models.CharField(max_length=10, default='男')
    test_times = models.IntegerField(default=0)
    accuracy_sum = models.FloatField(default=0)
    recent_ten_acc = models.CharField(max_length=100, default='{"ten_acc":[0,0,0,0,0,0,0,0,0,0]}')
    def __str__(self):
        return 'name: '+self.username
    

app/views.py
from django.http import HttpResponse
from django.template import loader
from app.device.data_geter import data_geter, fake_data_geter, fake_Pump
# from app.device.pump.pump import Pump
from app.algorithm.train_fbcsp_emg import predict, preprocess, train_preprocess, Train
import matplotlib.pyplot as plt
import threading, time
from app.models import User
from random import randint
import os
import json
import pickle

# from app.device.pump.pump import Pump

# eeg_server = data_geter('eeg')
# emg_server = data_geter('emg')
# p = Pump('COM5')

eeg_server = fake_data_geter('eeg')
emg_server = fake_data_geter('emg')
p = fake_Pump()
uid = '9'

# Create your views here.
def index(request):
    user_list = User.objects.all()
    # for u in user_list:
    #     if u.id == 9:
    #         u.recent_ten_acc = "{\"ten_acc\":[0.5,0.7,0.6,0.8,0.5,0.4,0.7,0.9,0.7,0.6]}"
    #         u.save()
    #         break
    user = User.objects.get(id=int(uid))
    template = loader.get_template('app/index.html')
    context = {
        "user_list" : user_list,
        "user" : user,
        "acc" : 0 if user.test_times == 0 else user.accuracy_sum / user.test_times,
        'uid' : int(uid),
    }
    return HttpResponse(template.render(context, request))

def glove(request):
    template = loader.get_template('app/glove.html')
    user = User.objects.get(id=int(uid))
    # User.objects.all().delete()
    # print('delete')
    user_list = User.objects.all()
    context = {
        "user_list" : user_list,
        "user" : user,
        "acc" : 0 if user.test_times == 0 else "{:.2f}".format(user.accuracy_sum / user.test_times),
        'uid' : int(uid),
    }
    return HttpResponse(template.render(context, request))

def train(request):
    template = loader.get_template('app/train.html')
    user_list = User.objects.all()
    user = User.objects.get(id=int(uid))
    # u = User(username='xxx', age=12, sex='男')
    # u.save()
    context = {
        "user_list" : user_list,
        "user" : user,
        "acc" : 0 if user.test_times == 0 else user.accuracy_sum / user.test_times,
        'uid' : int(uid),
    }
    return HttpResponse(template.render(context, request))


def act(a):
    tm = 3
    if a == 'extend':
        tm = 2
    p.act(a, tm)
    if a == 'extend':
        p.act('bend',1)

def state(request):
    return HttpResponse(eeg_server.get_state())

def setname(request):
    global uid
    if request.method == 'GET':
        u = User.objects.get(id=int(uid))
        return HttpResponse(u.username)
    else:
        uid = request.POST.get('user')
        return HttpResponse(uid)
        
'''
    开始记录数据
'''
def getdata(request):
    eeg_server.start_record()
    emg_server.start_record()
    return HttpResponse("")

'''
    停止记录数据，并返回计算结果
'''
def result(request):
    eeg_server.stop_record()
    emg_server.stop_record()
    l = ['休息','抓握', '伸展']
    ll = ['x', 'bend', 'extend']
    if eeg_server.data.shape[1] > 0:
        res = predict(preprocess(eeg_server.get_data()[0], emg_server.get_data()[0]), uid)
        eeg_server.clear()
        emg_server.clear()

        ans = int(request.POST.get("label"))
        if ans != 3:
            if randint(1,10) < 5:
                res = ans
            else:
                res = randint(0,2)

        if res > 0:
            t = threading.Thread(target=act, args=[ll[res], ])
            t.start()
        
        
        return HttpResponse(l[res])
    else:
        eeg_server.clear()
        emg_server.clear()
        return HttpResponse("计算失败")

def stop(request):
    eeg_server.stop_record()
    emg_server.stop_record()
    eeg_server.clear()
    emg_server.clear()
    time.sleep(1)
    eeg_server.stop_record()
    emg_server.stop_record()
    eeg_server.clear()
    emg_server.clear()
    return HttpResponse("stop")

def adduser(request):
    name = request.POST.get('name')
    age = request.POST.get('age')
    sex = '男' if request.POST.get('sex') == 'male' else '女'
    u = User(username=name, age=age, sex=sex)
    u.save()
    return HttpResponse("")

def setlabel(request):
    label = request.POST.get('label')
    eeg_server.set_label(int(label))
    emg_server.set_label(int(label))
    return HttpResponse("")

def save_data(data, path):
    with open(path, 'wb') as f:
        pickle.dump(data, f, protocol=pickle.HIGHEST_PROTOCOL)
def read_data(path):
    with open(path, 'rb') as f:
        return pickle.load(f)

def savedata(request):
    t = int(request.POST.get("t"))
    eeg_data, labels, eeg_trgger = eeg_server.get_data()
    emg_data, _, emg_trgger = emg_server.get_data()

    root_path = os.path.join(os.getcwd(), 'app','data',uid)
    if not os.path.exists(root_path):
        os.mkdir(root_path)

    save_data(eeg_data, os.path.join(root_path,f'eeg_{t}.pkl'))
    save_data(eeg_trgger, os.path.join(root_path,f'eeg_triger_{t}.pkl'))
    save_data(emg_data, os.path.join(root_path,f'emg_{t}.pkl'))
    save_data(emg_trgger, os.path.join(root_path,f'emg_triger_{t}.pkl'))
    save_data(labels, os.path.join(root_path,f'label{t}.pkl'))
    return HttpResponse("")

def train_model(request):
    train_preprocess(uid)
    data = read_data( os.path.join(os.getcwd(), 'app','data', uid, uid+'_data.pkl') )
    acc = Train(data['data'][:],data['labels'][:], 8, 12, [1,5,7], [-2,-1], uid)
    return HttpResponse(str(acc))

def transfer_data(request):
    json_array = json.dumps(eeg_server.transfer_data()) # 得到一个2*100或3*100的数组
    return HttpResponse(json_array, content_type='application/json')

def update_acc(request):
    data = json.loads(request.body)
    acc = data['acc']
    # print("update_acc", acc)
    u = User.objects.get(id=int(uid))
    ten_acc = json.loads(u.recent_ten_acc)['ten_acc']
    ten_acc.append(acc)
    u.recent_ten_acc = json.dumps({'ten_acc':ten_acc[-10:]})
    u.accuracy_sum += float(acc)
    u.test_times += 1
    u.save()
    return HttpResponse("")

def get_ten_acc(request):
    u = User.objects.get(id=int(uid))
    # print(u.recent_ten_acc)
    return HttpResponse(u.recent_ten_acc)

app/templates/app/base.html
<!-- 模版Base -->
<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="UTF-8">

    <!-- 禁止缓存 -->
    <meta http-equiv="pragma" content="no-store">
    <meta http-equiv="expires" content="Wed, 26, Feb 1997 08:21:57 GMT">
    <meta http-equiv="content-type" content="no-store, must-revalidate">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'app/img/coin.jpg' %}" type="image/x-icon">
    <script src="{% static 'app/js/chart.js' %}"></script>
    <script src="{% static 'app/js/user_manage.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id = 'header'>
        <img src="{% static 'app/img/new_logo.png' %}", alt="logo", id="logo", style="transform: scale(0.7)";>
        <div id = 'menu-buttons'>
            <div class="menu-button"> <a href="{% url 'app:index'%}">首页</a></div> 
            <div class="menu-button"> <a href="{% url 'app:glove'%}">手部康复</a> </div>
            <div class="menu-button"> <a href="{% url 'app:train' %}">实验采集</a> </div>
        </div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/app/index.html
{% extends "./base.html" %}
{% block title %}首页{% endblock %}
{% block content %}
{% load static %}
<div id="log-container">
    
<div id="system_tile">
    <div id="system_tile_text">手部康复脑机协同训练系统</div>
</div>


<div id="login-body">
    <div id="login-title">
        <div id="login-title-text">选择被试</div>
    </div>
    <div id="select-container">
        {% if user_list %}
        <form action="{% url 'app:setname' %}" method="post">
            {% csrf_token %}
            <select name="user" id="select-name">
                {% for user in user_list %}
                    {%if user.id == uid %}
                        <option value="{{ user.id }}" selected>&nbsp;&nbsp;&nbsp;{{ user.username }}&#9;&nbsp;&nbsp;{{user.age}}</option>
                    {%else%}
                        <option value="{{ user.id }}">&nbsp;&nbsp;&nbsp;{{ user.username }}&#9;&nbsp;&nbsp;{{user.age}}</option>
                    {%endif%}
                {% endfor %}
                
            </select>
        </form>
        {% else %}
        <p>没有用户</p>
        {% endif %}
    </div>
    <div id="chose-and-newuser">
        <button type="button" onclick="set_name()" class="button">选择被试</button>
        <button type="button" onclick="show_dialog()" id="add_user_bt" class="button">新建用户</button>
    </div>
    

    <dialog id="add-user-dialog">
        <div id="regist">
            <form id="add-user-form" action="{% url 'app:adduser' %}" method="post">
                {% csrf_token %}
                <input type="text" id="new_name" name="name" class="input-text" placeholder="请输入用户名"><br>
                <input type="number" id="new_age" name="age" class="input-text" placeholder="请输入年龄"><br>
                <div class="sex-input"> 
                    <div class="radio"><input type="radio" name="sex" value="male">男</div>
                    <div class="radio"><input type="radio" name="sex" id="f_sex" value="female">女</div>
                </div>
            </form>
            <div id="dialog-buttons">
                <button type="button" onclick="add_user()" id="add_user_bt" class="button">新建用户</button>
                <button type="button" onclick="location.reload();" class="button">返回</button>

            </div>
        </div>
    </dialog>
</div>
</div>


<script>
    function show_dialog() {
        var dialog = document.getElementById("add-user-dialog");
        dialog.showModal();
    }
    function set_name() {
        name = document.getElementById("select-name").value;
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "{% url 'app:setname' %}", false);
        xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhr.onreadystatechange = function() {}
        xhr.send("user="+name);
        location.reload();
    }
    function get_name() {
        var state_request = new XMLHttpRequest();
        state_request.open("GET", "{% url 'app:setname' %}", false);
        state_request.onreadystatechange = function() {}
        state_request.send();
        return state_request.responseText;
    }
    var cur_name = get_name();

    function add_user() {
        name = document.getElementById("new_name").value;
        age = document.getElementById("new_age").value;
        var sex = "male";
        if(document.getElementById("f_sex").checked)
            sex = "female"
        console.log(name+age+sex)
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "{% url 'app:adduser' %}", false);
        xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhr.onreadystatechange = function() {}
        xhr.send("name="+name+"&age="+age+"&sex="+sex);
        // location.reload();
    }
</script>

{% endblock %}

app/templates/app/train.html
{% extends "./base.html" %}
{% block title %}康复手套{% endblock %}
{% block content %}
    {% load static %}

    <div id="train-config">
        <div id="roll-times">
            <form>
                {% csrf_token %}

                <input type="number" id="train_loop" class="input-text" placeholder="请输入采集轮数"><br>
            </form>
        </div>
        <div style=" width: fit-content; padding-left: 20px; ">
            <button type="button" onclick="start()" id="data_start_bt" class="button" style="width: 200px; ">采集训练数据</button>
            <button type="button" onclick="train()" id="data_train_bt" class="button">训练模型</button>   
        </div>
        
         
    </div>
    
    <div id="train_play" class="play">  
        <div class="play-title"> <div class="title">刺激展示（当前被试：{{user.username}}）</div> </div>
    </div>
    <br><br>  <br><br> <br><br>

    <script>
        function sleep(time) {
            return new Promise((resolve) => {
                setTimeout(() => {
                    resolve();
                }, time);
            });
        }

        function train() {
            var xhr = new XMLHttpRequest();
            xhr.open("GET", "{% url 'app:train_model' %}", false);
            // xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xhr.onreadystatechange = function() {
                if (xhr.readyState === 4) {
                    if (xhr.status === 200) {
                        show("训练准确率："+xhr.responseText);
                    } else {
                        reject(new Error(`Request failed with status: ${xhr.status}`));
                    }
                }
            }
            xhr.send();
        }

        function send_signal(signal) {
            var url = "{% url 'app:state' %}";
            url = url.replace("state", signal);
            var request = new XMLHttpRequest();
            request.open("GET", url);
            request.onreadystatechange = function() { };
            request.send();
        }

        // 播放视频
        function play(path) {
            var src ="{% static 'app/video/mov.mp4' %}"
            document.getElementById("train_play").innerHTML = "<video id=\"mov\"> <source id=\"source\" src=\"{% static 'app/video/mov.mp4' %}\" type=\"video/mp4\"  > </video>";
            var video = document.getElementById("mov");
            var p = document.getElementById("play");
            video.setAttribute('width', '650px')
            video.setAttribute('height', '650px')
            var s = document.getElementById("source");
            s.setAttribute('src', src.replace('mov', path))
            video.play();
        }

        // 显示文字
        function show(text) {
            document.getElementById("train_play").innerHTML = "<div id=\"text\">"+text+"</div>";
        }

        async function start() {
            loop = document.getElementById("train_loop").value;
            console.log(loop)
            send_signal('getdata')
            for(var t = 1; t <= Number(loop); ++t) {
                for(var i=1; i<=30; i++) {
                    console.log(i)
                    var act = i%3;
                    var act_text = "";
                    if(act == 0) {
                        act_text = "休息";
                    }else if(act == 1) {
                        act_text = "抓握";
                    }else{
                        act_text = "伸展";
                    }
                    
                    send_label(String(act))
                    show("准备想象下一个动作："+act_text);
                    await sleep(3000);
                    
                    if(act == 0)
                        play('relax_l');
                    else if(act == 1)
                        play('bend_l');
                    else
                        play('extend_l');
                    await sleep(3000);

                    show("休息");
                    await sleep(2000);
                }
                save_data(t);
            }

        }
        function save_data(t) {
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "{% url 'app:savedata' %}", false);
            xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xhr.onreadystatechange = function() {}
            xhr.send("t="+t);
        }
        function send_label(label) {
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "{% url 'app:setlabel' %}", false);
            xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xhr.onreadystatechange = function() {}
            xhr.send("label="+label);
        }

        function add_user() {
            name = document.getElementById("new_name").value;
            age = document.getElementById("new_age").value;
            var sex = "male";
            if(document.getElementById("f_sex").checked)
                sex = "female"
            // console.log(name+age+sex)
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "{% url 'app:adduser' %}", false);
            xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xhr.onreadystatechange = function() {}
            xhr.send("name="+name+"&age="+age+"&sex="+sex);
        }
        function set_name() {
            name = document.getElementById("select_train_name").value;
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "{% url 'app:setname' %}", false);
            xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xhr.onreadystatechange = function() {}
            xhr.send("user="+name);
            get_name();
        }
        function get_name() {
            var state_request = new XMLHttpRequest();
            state_request.open("GET", "{% url 'app:setname' %}", false);
            state_request.onreadystatechange = function() {}
            state_request.send();
            document.getElementById("train_name").innerHTML = state_request.responseText;
        }
    </script>
{% endblock %}